/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './recipe-start.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './recipe-start.component';
const styles_RecipeStartComponent:any[] = [i0.styles];
export const RenderType_RecipeStartComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_RecipeStartComponent,data:{}});
export function View_RecipeStartComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h3',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['Please select a Recipe!'])),(_l()(),i1.ɵted((null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_RecipeStartComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-recipe-start',
      ([] as any[]),(null as any),(null as any),(null as any),View_RecipeStartComponent_0,
      RenderType_RecipeStartComponent)),i1.ɵdid(114688,(null as any),0,i2.RecipeStartComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const RecipeStartComponentNgFactory:i1.ComponentFactory<i2.RecipeStartComponent> = i1.ɵccf('app-recipe-start',
    i2.RecipeStartComponent,View_RecipeStartComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMveWFveGkvRG9jdW1lbnRzL0pvYmh1bnRpbmcvUHJvamVjdC9NRUFOX1N0YWNrL2Fzc2V0cy9hcHAvcmVjaXBlcy9yZWNpcGUtc3RhcnQvcmVjaXBlLXN0YXJ0LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy95YW94aS9Eb2N1bWVudHMvSm9iaHVudGluZy9Qcm9qZWN0L01FQU5fU3RhY2svYXNzZXRzL2FwcC9yZWNpcGVzL3JlY2lwZS1zdGFydC9yZWNpcGUtc3RhcnQuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMveWFveGkvRG9jdW1lbnRzL0pvYmh1bnRpbmcvUHJvamVjdC9NRUFOX1N0YWNrL2Fzc2V0cy9hcHAvcmVjaXBlcy9yZWNpcGUtc3RhcnQvcmVjaXBlLXN0YXJ0LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMveWFveGkvRG9jdW1lbnRzL0pvYmh1bnRpbmcvUHJvamVjdC9NRUFOX1N0YWNrL2Fzc2V0cy9hcHAvcmVjaXBlcy9yZWNpcGUtc3RhcnQvcmVjaXBlLXN0YXJ0LmNvbXBvbmVudC50cy5SZWNpcGVTdGFydENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMz5QbGVhc2Ugc2VsZWN0IGEgUmVjaXBlITwvaDM+XG4iLCI8YXBwLXJlY2lwZS1zdGFydD48L2FwcC1yZWNpcGUtc3RhcnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUk7YUFBQSw2Q0FBNEI7TUFBQTs7O29CQ0FoQztNQUFBO3FDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
