/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './core.module';
import * as i2 from './home/home.component.ngfactory';
import * as i3 from '../shopping-list/shopping-list.component.ngfactory';
import * as i4 from '@angular/common';
import * as i5 from '@angular/router';
import * as i6 from '../shopping-list/shopping-list.service';
import * as i7 from '../recipes/recipe.service';
import * as i8 from '../shared/data-storage.service';
import * as i9 from '@angular/http';
import * as i10 from '../errors/error.service';
import * as i11 from '../auth/auth.service';
import * as i12 from '../auth/auth-guard.service';
import * as i13 from '../shared/shared.module';
import * as i14 from './home/home.component';
import * as i15 from '../shopping-list/shopping-list.component';
import * as i16 from '../app-routing.module';
export const CoreModuleNgFactory:i0.NgModuleFactory<i1.CoreModule> = i0.ɵcmf(i1.CoreModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.HomeComponentNgFactory,i3.ShoppingListComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i4.NgLocalization,i4.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(5120,i5.ActivatedRoute,i5.ɵf,[i5.Router]),i0.ɵmpd(4608,
          i5.PreloadAllModules,i5.PreloadAllModules,([] as any[])),i0.ɵmpd(6144,i5.PreloadingStrategy,
          (null as any),[i5.PreloadAllModules]),i0.ɵmpd(135680,i5.RouterPreloader,
          i5.RouterPreloader,[i5.Router,i0.NgModuleFactoryLoader,i0.Compiler,i0.Injector,
              i5.PreloadingStrategy]),i0.ɵmpd(4608,i5.NoPreloading,i5.NoPreloading,
          ([] as any[])),i0.ɵmpd(5120,i0.NgProbeToken,() => {
        return [i5.ɵb()];
      },([] as any[])),i0.ɵmpd(4608,i5.ɵg,i5.ɵg,[i0.Injector]),i0.ɵmpd(5120,i0.APP_INITIALIZER,
          (p0_0:any) => {
            return [i5.ɵh(p0_0)];
          },[i5.ɵg]),i0.ɵmpd(5120,i5.ROUTER_INITIALIZER,i5.ɵi,[i5.ɵg]),i0.ɵmpd(5120,
          i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i5.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i6.ShoppingListService,i6.ShoppingListService,
          ([] as any[])),i0.ɵmpd(4608,i7.RecipeService,i7.RecipeService,[i6.ShoppingListService]),
          i0.ɵmpd(4608,i8.DataStorageService,i8.DataStorageService,[i9.Http,i7.RecipeService,
              i10.ErrorService]),i0.ɵmpd(4608,i11.AuthService,i11.AuthService,[i9.Http,
              i10.ErrorService]),i0.ɵmpd(4608,i12.AuthGuard,i12.AuthGuard,[i11.AuthService]),
          i0.ɵmpd(512,i4.CommonModule,i4.CommonModule,([] as any[])),i0.ɵmpd(512,i13.SharedModule,
              i13.SharedModule,([] as any[])),i0.ɵmpd(1024,i5.ɵa,i5.ɵd,[[3,i5.Router]]),
          i0.ɵmpd(512,i5.UrlSerializer,i5.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,
              i5.ChildrenOutletContexts,i5.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,
              i5.ROUTER_CONFIGURATION,{preloadingStrategy:i5.PreloadAllModules},([] as any[])),
          i0.ɵmpd(1024,i4.LocationStrategy,i5.ɵc,[i4.PlatformLocation,[2,i4.APP_BASE_HREF],
              i5.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i4.Location,i4.Location,[i4.LocationStrategy]),
          i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,[i0.Compiler,
              [2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i5.ROUTES,() => {
            return [[{path:'',component:i14.HomeComponent},{path:'recipes',loadChildren:'./recipes/recipes.module#RecipesModule'},
                {path:'shopping-list',component:i15.ShoppingListComponent}]];
          },([] as any[])),i0.ɵmpd(1024,i5.Router,i5.ɵe,[i0.ApplicationRef,i5.UrlSerializer,
              i5.ChildrenOutletContexts,i4.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i5.ROUTES,i5.ROUTER_CONFIGURATION,[2,i5.UrlHandlingStrategy],
              [2,i5.RouteReuseStrategy]]),i0.ɵmpd(512,i5.RouterModule,i5.RouterModule,
              [[2,i5.ɵa],[2,i5.Router]]),i0.ɵmpd(512,i16.AppRoutingModule,i16.AppRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i1.CoreModule,i1.CoreModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMveWFveGkvRG9jdW1lbnRzL0pvYmh1bnRpbmcvUHJvamVjdC9NRUFOX1N0YWNrL2Fzc2V0cy9hcHAvY29yZS9jb3JlLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy95YW94aS9Eb2N1bWVudHMvSm9iaHVudGluZy9Qcm9qZWN0L01FQU5fU3RhY2svYXNzZXRzL2FwcC9jb3JlL2NvcmUubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
