/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './auth.module';
import * as i2 from './signup/signup.component.ngfactory';
import * as i3 from './signin/signin.component.ngfactory';
import * as i4 from '@angular/forms';
import * as i5 from '@angular/router';
import * as i6 from './auth-routing.module';
import * as i7 from './signup/signup.component';
import * as i8 from './signin/signin.component';
export const AuthModuleNgFactory:i0.NgModuleFactory<i1.AuthModule> = i0.ɵcmf(i1.AuthModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.SignupComponentNgFactory,i3.SigninComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i4.ɵi,i4.ɵi,([] as any[])),i0.ɵmpd(4608,
          i4.FormBuilder,i4.FormBuilder,([] as any[])),i0.ɵmpd(512,i4.ɵba,i4.ɵba,([] as any[])),
          i0.ɵmpd(512,i4.FormsModule,i4.FormsModule,([] as any[])),i0.ɵmpd(512,i4.ReactiveFormsModule,
              i4.ReactiveFormsModule,([] as any[])),i0.ɵmpd(512,i5.RouterModule,i5.RouterModule,
              [[2,i5.ɵa],[2,i5.Router]]),i0.ɵmpd(512,i6.AuthRoutingModule,i6.AuthRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i1.AuthModule,i1.AuthModule,([] as any[])),
          i0.ɵmpd(1024,i5.ROUTES,() => {
            return [[{path:'signup',component:i7.SignupComponent},{path:'signin',component:i8.SigninComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMveWFveGkvRG9jdW1lbnRzL0pvYmh1bnRpbmcvUHJvamVjdC9NRUFOX1N0YWNrL2Fzc2V0cy9hcHAvYXV0aC9hdXRoLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy95YW94aS9Eb2N1bWVudHMvSm9iaHVudGluZy9Qcm9qZWN0L01FQU5fU3RhY2svYXNzZXRzL2FwcC9hdXRoL2F1dGgubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
