/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './auth-routing.module';
import * as i2 from './signup/signup.component.ngfactory';
import * as i3 from './signin/signin.component.ngfactory';
import * as i4 from '@angular/router';
import * as i5 from './signup/signup.component';
import * as i6 from './signin/signin.component';
export const AuthRoutingModuleNgFactory:i0.NgModuleFactory<i1.AuthRoutingModule> = i0.ɵcmf(i1.AuthRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.SignupComponentNgFactory,i3.SigninComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(512,i4.RouterModule,i4.RouterModule,[[2,i4.ɵa],
          [2,i4.Router]]),i0.ɵmpd(512,i1.AuthRoutingModule,i1.AuthRoutingModule,([] as any[])),
          i0.ɵmpd(1024,i4.ROUTES,() => {
            return [[{path:'signup',component:i5.SignupComponent},{path:'signin',component:i6.SigninComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMveWFveGkvRG9jdW1lbnRzL0pvYmh1bnRpbmcvUHJvamVjdC9NRUFOX1N0YWNrL2Fzc2V0cy9hcHAvYXV0aC9hdXRoLXJvdXRpbmcubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL3lhb3hpL0RvY3VtZW50cy9Kb2JodW50aW5nL1Byb2plY3QvTUVBTl9TdGFjay9hc3NldHMvYXBwL2F1dGgvYXV0aC1yb3V0aW5nLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
