/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './recipes-routing.module';
import * as i2 from './recipes.component.ngfactory';
import * as i3 from './recipe-start/recipe-start.component.ngfactory';
import * as i4 from './recipe-edit/recipe-edit.component.ngfactory';
import * as i5 from './recipe-detail/recipe-detail.component.ngfactory';
import * as i6 from '../auth/auth-guard.service';
import * as i7 from '../auth/auth.service';
import * as i8 from '@angular/router';
import * as i9 from './recipes.component';
import * as i10 from './recipe-start/recipe-start.component';
import * as i11 from './recipe-edit/recipe-edit.component';
import * as i12 from './recipe-detail/recipe-detail.component';
export const RecipesRoutingModuleNgFactory:i0.NgModuleFactory<i1.RecipesRoutingModule> = i0.ɵcmf(i1.RecipesRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.RecipesComponentNgFactory,i3.RecipeStartComponentNgFactory,i4.RecipeEditComponentNgFactory,
              i5.RecipeDetailComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i6.AuthGuard,i6.AuthGuard,[i7.AuthService]),
          i0.ɵmpd(512,i8.RouterModule,i8.RouterModule,[[2,i8.ɵa],[2,i8.Router]]),i0.ɵmpd(512,
              i1.RecipesRoutingModule,i1.RecipesRoutingModule,([] as any[])),i0.ɵmpd(1024,
              i8.ROUTES,() => {
                return [[{path:'',component:i9.RecipesComponent,children:[{path:'',
                    component:i10.RecipeStartComponent},{path:'new',component:i11.RecipeEditComponent,
                    canActivate:[i6.AuthGuard]},{path:':id',component:i12.RecipeDetailComponent},
                    {path:':id/edit',component:i11.RecipeEditComponent,canActivate:[i6.AuthGuard]}]}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMveWFveGkvRG9jdW1lbnRzL0pvYmh1bnRpbmcvUHJvamVjdC9NRUFOX1N0YWNrL2Fzc2V0cy9hcHAvcmVjaXBlcy9yZWNpcGVzLXJvdXRpbmcubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL3lhb3hpL0RvY3VtZW50cy9Kb2JodW50aW5nL1Byb2plY3QvTUVBTl9TdGFjay9hc3NldHMvYXBwL3JlY2lwZXMvcmVjaXBlcy1yb3V0aW5nLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
