/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './recipes.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './recipe-list/recipe-list.component.ngfactory';
import * as i3 from './recipe-list/recipe-list.component';
import * as i4 from './recipe.service';
import * as i5 from '@angular/router';
import * as i6 from './recipes.component';
const styles_RecipesComponent:any[] = [i0.styles];
export const RenderType_RecipesComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_RecipesComponent,data:{}});
export function View_RecipesComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),13,'div',[['class',
      'row']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          4,'div',[['class','col-md-5']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n    '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-recipe-list',([] as any[]),
          (null as any),(null as any),(null as any),i2.View_RecipeListComponent_0,
          i2.RenderType_RecipeListComponent)),i1.ɵdid(245760,(null as any),0,i3.RecipeListComponent,
          [i4.RecipeService,i5.Router,i5.ActivatedRoute],(null as any),(null as any)),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵted((null as any),['\n  '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),4,'div',[['class','col-md-7']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(16777216,(null as any),
          (null as any),1,'router-outlet',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),i1.ɵdid(212992,(null as any),
          0,i5.RouterOutlet,[i5.ChildrenOutletContexts,i1.ViewContainerRef,i1.ComponentFactoryResolver,
              [8,(null as any)],i1.ChangeDetectorRef],(null as any),(null as any)),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵted((null as any),['\n'])),
      (_l()(),i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    _ck(_v,5,0);
    _ck(_v,11,0);
  },(null as any));
}
export function View_RecipesComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-recipes',
      ([] as any[]),(null as any),(null as any),(null as any),View_RecipesComponent_0,
      RenderType_RecipesComponent)),i1.ɵdid(114688,(null as any),0,i6.RecipesComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const RecipesComponentNgFactory:i1.ComponentFactory<i6.RecipesComponent> = i1.ɵccf('app-recipes',
    i6.RecipesComponent,View_RecipesComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMveWFveGkvRG9jdW1lbnRzL0pvYmh1bnRpbmcvUHJvamVjdC9NRUFOX1N0YWNrL2Fzc2V0cy9hcHAvcmVjaXBlcy9yZWNpcGVzLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy95YW94aS9Eb2N1bWVudHMvSm9iaHVudGluZy9Qcm9qZWN0L01FQU5fU3RhY2svYXNzZXRzL2FwcC9yZWNpcGVzL3JlY2lwZXMuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMveWFveGkvRG9jdW1lbnRzL0pvYmh1bnRpbmcvUHJvamVjdC9NRUFOX1N0YWNrL2Fzc2V0cy9hcHAvcmVjaXBlcy9yZWNpcGVzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMveWFveGkvRG9jdW1lbnRzL0pvYmh1bnRpbmcvUHJvamVjdC9NRUFOX1N0YWNrL2Fzc2V0cy9hcHAvcmVjaXBlcy9yZWNpcGVzLmNvbXBvbmVudC50cy5SZWNpcGVzQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cInJvd1wiPlxuICA8ZGl2IGNsYXNzPVwiY29sLW1kLTVcIj5cbiAgICA8YXBwLXJlY2lwZS1saXN0PjwvYXBwLXJlY2lwZS1saXN0PlxuICA8L2Rpdj5cbiAgPGRpdiBjbGFzcz1cImNvbC1tZC03XCI+XG4gICAgPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PlxuICA8L2Rpdj5cbjwvZGl2PlxuIiwiPGFwcC1yZWNpcGVzPjwvYXBwLXJlY2lwZXM+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQWlCLHlDQUNmO1VBQUE7VUFBQSw4QkFBc0I7TUFDcEI7VUFBQTsyQ0FBQSxVQUFBO1VBQUE7TUFBbUMseUNBQy9CO01BQ047VUFBQTtNQUFzQiwyQ0FDcEI7VUFBQTtVQUFBLG1EQUFBO1VBQUE7Y0FBQTtNQUErQix5Q0FDM0I7TUFDRjtJQUxGO0lBR0E7Ozs7b0JDTEo7TUFBQTtpQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
