/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './recipes.module';
import * as i2 from './recipes.component.ngfactory';
import * as i3 from './recipe-start/recipe-start.component.ngfactory';
import * as i4 from './recipe-edit/recipe-edit.component.ngfactory';
import * as i5 from './recipe-detail/recipe-detail.component.ngfactory';
import * as i6 from '@angular/common';
import * as i7 from '@angular/forms';
import * as i8 from '../auth/auth-guard.service';
import * as i9 from '../auth/auth.service';
import * as i10 from '@angular/router';
import * as i11 from './recipes-routing.module';
import * as i12 from '../shared/shared.module';
import * as i13 from './recipes.component';
import * as i14 from './recipe-start/recipe-start.component';
import * as i15 from './recipe-edit/recipe-edit.component';
import * as i16 from './recipe-detail/recipe-detail.component';
export const RecipesModuleNgFactory:i0.NgModuleFactory<i1.RecipesModule> = i0.ɵcmf(i1.RecipesModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.RecipesComponentNgFactory,i3.RecipeStartComponentNgFactory,i4.RecipeEditComponentNgFactory,
              i5.RecipeDetailComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i6.NgLocalization,i6.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(4608,i7.FormBuilder,i7.FormBuilder,([] as any[])),
          i0.ɵmpd(4608,i7.ɵi,i7.ɵi,([] as any[])),i0.ɵmpd(4608,i8.AuthGuard,i8.AuthGuard,
              [i9.AuthService]),i0.ɵmpd(512,i6.CommonModule,i6.CommonModule,([] as any[])),
          i0.ɵmpd(512,i7.ɵba,i7.ɵba,([] as any[])),i0.ɵmpd(512,i7.ReactiveFormsModule,
              i7.ReactiveFormsModule,([] as any[])),i0.ɵmpd(512,i10.RouterModule,i10.RouterModule,
              [[2,i10.ɵa],[2,i10.Router]]),i0.ɵmpd(512,i11.RecipesRoutingModule,i11.RecipesRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i12.SharedModule,i12.SharedModule,([] as any[])),
          i0.ɵmpd(512,i1.RecipesModule,i1.RecipesModule,([] as any[])),i0.ɵmpd(1024,
              i10.ROUTES,() => {
                return [[{path:'',component:i13.RecipesComponent,children:[{path:'',
                    component:i14.RecipeStartComponent},{path:'new',component:i15.RecipeEditComponent,
                    canActivate:[i8.AuthGuard]},{path:':id',component:i16.RecipeDetailComponent},
                    {path:':id/edit',component:i15.RecipeEditComponent,canActivate:[i8.AuthGuard]}]}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMveWFveGkvRG9jdW1lbnRzL0pvYmh1bnRpbmcvUHJvamVjdC9NRUFOX1N0YWNrL2Fzc2V0cy9hcHAvcmVjaXBlcy9yZWNpcGVzLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy95YW94aS9Eb2N1bWVudHMvSm9iaHVudGluZy9Qcm9qZWN0L01FQU5fU3RhY2svYXNzZXRzL2FwcC9yZWNpcGVzL3JlY2lwZXMubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
