/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app-routing.module';
import * as i2 from './core/home/home.component.ngfactory';
import * as i3 from './shopping-list/shopping-list.component.ngfactory';
import * as i4 from '@angular/router';
import * as i5 from '@angular/common';
import * as i6 from './core/home/home.component';
import * as i7 from './shopping-list/shopping-list.component';
export const AppRoutingModuleNgFactory:i0.NgModuleFactory<i1.AppRoutingModule> = i0.ɵcmf(i1.AppRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.HomeComponentNgFactory,i3.ShoppingListComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(5120,i4.ActivatedRoute,i4.ɵf,[i4.Router]),i0.ɵmpd(4608,
          i4.PreloadAllModules,i4.PreloadAllModules,([] as any[])),i0.ɵmpd(6144,i4.PreloadingStrategy,
          (null as any),[i4.PreloadAllModules]),i0.ɵmpd(135680,i4.RouterPreloader,
          i4.RouterPreloader,[i4.Router,i0.NgModuleFactoryLoader,i0.Compiler,i0.Injector,
              i4.PreloadingStrategy]),i0.ɵmpd(4608,i4.NoPreloading,i4.NoPreloading,
          ([] as any[])),i0.ɵmpd(5120,i0.NgProbeToken,() => {
        return [i4.ɵb()];
      },([] as any[])),i0.ɵmpd(4608,i4.ɵg,i4.ɵg,[i0.Injector]),i0.ɵmpd(5120,i0.APP_INITIALIZER,
          (p0_0:any) => {
            return [i4.ɵh(p0_0)];
          },[i4.ɵg]),i0.ɵmpd(5120,i4.ROUTER_INITIALIZER,i4.ɵi,[i4.ɵg]),i0.ɵmpd(5120,
          i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i4.ROUTER_INITIALIZER]),i0.ɵmpd(1024,i4.ɵa,i4.ɵd,[[3,i4.Router]]),i0.ɵmpd(512,
          i4.UrlSerializer,i4.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,i4.ChildrenOutletContexts,
          i4.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,i4.ROUTER_CONFIGURATION,
          {preloadingStrategy:i4.PreloadAllModules},([] as any[])),i0.ɵmpd(1024,i5.LocationStrategy,
          i4.ɵc,[i5.PlatformLocation,[2,i5.APP_BASE_HREF],i4.ROUTER_CONFIGURATION]),
          i0.ɵmpd(512,i5.Location,i5.Location,[i5.LocationStrategy]),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i4.ROUTES,() => {
            return [[{path:'',component:i6.HomeComponent},{path:'recipes',loadChildren:'./recipes/recipes.module#RecipesModule'},
                {path:'shopping-list',component:i7.ShoppingListComponent}]];
          },([] as any[])),i0.ɵmpd(1024,i4.Router,i4.ɵe,[i0.ApplicationRef,i4.UrlSerializer,
              i4.ChildrenOutletContexts,i5.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i4.ROUTES,i4.ROUTER_CONFIGURATION,[2,i4.UrlHandlingStrategy],
              [2,i4.RouteReuseStrategy]]),i0.ɵmpd(512,i4.RouterModule,i4.RouterModule,
              [[2,i4.ɵa],[2,i4.Router]]),i0.ɵmpd(512,i1.AppRoutingModule,i1.AppRoutingModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMveWFveGkvRG9jdW1lbnRzL0pvYmh1bnRpbmcvUHJvamVjdC9NRUFOX1N0YWNrL2Fzc2V0cy9hcHAvYXBwLXJvdXRpbmcubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL3lhb3hpL0RvY3VtZW50cy9Kb2JodW50aW5nL1Byb2plY3QvTUVBTl9TdGFjay9hc3NldHMvYXBwL2FwcC1yb3V0aW5nLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
